### ISSUE TITLE
Traceparent propagation in OpenTelemetry::Integration::LWP::UserAgent ?

### ISSUE THREAD

**Issue by abh** [jjatria/perl-opentelemetry#10]
It seems like it'd be useful to have an option for OpenTelemetry::Integration::LWP::UserAgent to have it add Traceparent propagation.

**Comment by jjatria** [comment]
I imagine we'd need something like

``` perl
otel_propagator->inject(
    $request,
    undef,
    sub ( $carrier, $key, $value ) { $carrier->header( $key => $value ) },
);
```

This should also be added to the HTTP::Tiny integration for sure. Well spotted!

**Comment by jjatria** [comment]
The Ruby version exposes some common getters / setters so that you don't have to re-write them all every time. I've held off on that for now with the idea that we implement the infrastructure first, and worry about the quality-of-life changes later (when we know what makes the quality of our lives worse), but it's probably a good idea to start keeping a list somewhere.
